import { canonicalJson, stableHash } from "../stableHash";

describe("canonicalJson", () => {
  it("produces identical JSON for objects with different key orders", () => {
    const obj1 = { a: 1, b: 2, c: 3 };
    const obj2 = { c: 3, a: 1, b: 2 };

    const json1 = canonicalJson(obj1);
    const json2 = canonicalJson(obj2);

    expect(json1).toBe(json2);
  });

  it("produces identical JSON for nested objects with different key orders", () => {
    const obj1 = { outer: { z: 26, a: 1 }, x: "test" };
    const obj2 = { x: "test", outer: { a: 1, z: 26 } };

    const json1 = canonicalJson(obj1);
    const json2 = canonicalJson(obj2);

    expect(json1).toBe(json2);
  });

  it("distinguishes arrays with different orders", () => {
    const json1 = canonicalJson([1, 2, 3]);
    const json2 = canonicalJson([3, 2, 1]);

    expect(json1).not.toBe(json2);
  });

  it("handles arrays of objects with key order normalization", () => {
    const arr1 = canonicalJson([{ b: 2, a: 1 }, { z: 26, x: 24 }]);
    const arr2 = canonicalJson([{ a: 1, b: 2 }, { x: 24, z: 26 }]);

    expect(arr1).toBe(arr2);
  });

  it("throws on undefined", () => {
    expect(() => canonicalJson(undefined)).toThrow(/undefined/i);
  });

  it("throws on NaN", () => {
    expect(() => canonicalJson(NaN)).toThrow(/finite|NaN/i);
  });

  it("throws on Infinity", () => {
    expect(() => canonicalJson(Infinity)).toThrow(/finite|Infinity/i);
  });

  it("throws on -Infinity", () => {
    expect(() => canonicalJson(-Infinity)).toThrow(/finite|Infinity/i);
  });

  it("throws on circular reference", () => {
    const obj: any = { a: 1 };
    obj.self = obj;

    expect(() => canonicalJson(obj)).toThrow(/circular/i);
  });

  it("throws on function", () => {
    expect(() => canonicalJson(() => {})).toThrow(/function/i);
  });

  it("throws on symbol", () => {
    expect(() => canonicalJson(Symbol("test"))).toThrow(/symbol/i);
  });

  it("throws on bigint", () => {
    expect(() => canonicalJson(BigInt(123))).toThrow(/bigint/i);
  });

  it("handles null, boolean, number, string primitives", () => {
    expect(canonicalJson(null)).toBe("null");
    expect(canonicalJson(true)).toBe("true");
    expect(canonicalJson(false)).toBe("false");
    expect(canonicalJson(42)).toBe("42");
    expect(canonicalJson("hello")).toBe('"hello"');
  });

  it("handles empty objects and arrays", () => {
    expect(canonicalJson({})).toBe("{}");
    expect(canonicalJson([])).toBe("[]");
  });
});

describe("stableHash", () => {
  it("produces identical hashes for objects with different key orders", () => {
    const hash1 = stableHash({ a: 1, b: 2, c: 3 });
    const hash2 = stableHash({ c: 3, a: 1, b: 2 });

    expect(hash1).toBe(hash2);
  });

  it("produces different hashes for arrays with different orders", () => {
    const hash1 = stableHash([1, 2, 3]);
    const hash2 = stableHash([3, 2, 1]);

    expect(hash1).not.toBe(hash2);
  });

  it("produces a 64-character hex string (sha256)", () => {
    const hash = stableHash({ test: true });
    expect(hash).toMatch(/^[0-9a-f]{64}$/);
  });

  it("golden: known-value hash of a fixed object", () => {
    const obj = {
      id: "test-123",
      location: { lat: 40.7128, lng: -74.006 },
      stops: [
        { name: "A", duration: 30 },
        { name: "B", duration: 45 },
      ],
      active: true,
    };

    const hash = stableHash(obj);

    // This golden hash was generated by running canonicalJson on the object
    // and computing sha256. It is pinned here to detect any changes to the
    // hashing logic or the test object.
    expect(hash).toBe("2b79381506ee5faef6c0eea002125c6d1fc0a45e17b68ad81507c3d6466f0ed2");
  });

  it("throws on undefined value", () => {
    expect(() => stableHash(undefined)).toThrow();
  });

  it("throws on NaN value", () => {
    expect(() => stableHash(NaN)).toThrow();
  });

  it("throws on circular structure", () => {
    const obj: any = { a: 1 };
    obj.self = obj;
    expect(() => stableHash(obj)).toThrow();
  });
});

describe("shared (non-circular) references", () => {
  it("allows the same object under two keys — shared refs are content, not cycles", () => {
    const shared = { a: 1 };
    const doc = { x: shared, y: shared };
    // Must hash identically to the structurally-equal doc with distinct objects.
    expect(stableHash(doc)).toBe(stableHash({ x: { a: 1 }, y: { a: 1 } }));
  });

  it("still detects a genuine cycle through the ancestor chain", () => {
    const node: Record<string, unknown> = { a: 1 };
    node.self = node;
    expect(() => stableHash(node)).toThrow(/circular/);
  });
});
